<main>
    <div id="notiLive">
        <script>
            if (typeof live === "undefined") {
                var live = {
                    16: {
                        hourEnd: 16,
                        title: "Miền Nam",
                        url: "<?= $base_url ?>xo-so-mien-nam-xsmn.html"
                    },
                    17: {
                        hourEnd: 17,
                        title: "Miền Trung",
                        url: "<?= $base_url ?>xo-so-mien-trung-xsmt.html"
                    },
                    18: {
                        hourEnd: 18,
                        title: "Miền Bắc",
                        url: "<?= $base_url ?>xo-so-mien-bac-xsmb.html"
                    }
                };
                let date = new Date();
                $("#notiLiveTitle").html(live[date.getHours()].title);
                $("#notiLiveLink").attr('href', live[date.getHours()].url);
            }
        </script>
    </div>
    <div class="container">
        <div class="row">
            <div class="w-100">
                <nav aria-label="breadcrumb">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="<?= $base_url ?>" title="Trang chủ"><i
                                    class="icon-home"></i></a> </li>
                        <li class="breadcrumb-item active"><a href="<?= $base_url ?>bac-nho-lo-de-xsmb.html"
                                title="Bạc nhớ lô đề miền Bắc 2025">Bạc nhớ lô đề miền Bắc 2025</a> </li>
                        <script
                            type="application/ld+json">
                            {
                                "@context": "http:\/\/schema.org",
                                "@type": "BreadcrumbList",
                                "itemListElement": [{
                                    "@type": "ListItem",
                                    "position": 1,
                                    "item": {
                                        "@id": "\/",
                                        "name": "<i class='icon-home'><\/i>"
                                    }
                                }, {
                                    "@type": "ListItem",
                                    "position": 2,
                                    "item": {
                                        "@id": "\/bac-nho-lo-de-xsmb.html",
                                        "name": "Bạc nhớ lô đề miền Bắc 2025"
                                    }
                                }]
                            }
                        </script>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-610">
                <div class="bg-white rounded">
                    <h2 class="font-20 my-2"> <strong>Bạc nhớ lô đề miền Bắc 2025 – Dự đoán số siêu chuẩn</strong> </h2>
                    <div class="d-flex font-13 justify-content-between my-3 flex-wrap">
                        <div class="text-gray">
                            <div class="new-date"> Thứ hai, 26/01/2026 - 01:00 </div>
                            <div class="allRate"> <input type="range" value="0" step="0.25" id="backing5"
                                    style="display: none;">
                                <input type="text" value="page/151" hidden="" id="voteLink">
                                <div class="rateit rateit-font" data-rateit-backingfld="#backing5"
                                    data-rateit-resetable="false" data-rateit-ispreset="true" data-rateit-min="0"
                                    data-rateit-max="5" data-rateit-mode="font" data-rateit-icon=""
                                    style="font-family:fontawesome"> <button id="rateit-reset-2" type="button"
                                        data-role="none" class="rateit-reset" aria-label="reset rating"
                                        aria-controls="rateit-range-2" style="display: none;"><span></span></button>
                                    <div id="rateit-range-2" class="rateit-range" tabindex="0" role="slider"
                                        aria-label="rating" aria-owns="rateit-reset-2" aria-valuemin="0"
                                        aria-valuemax="5" aria-valuenow="0" aria-readonly="false">
                                        <div class="rateit-empty">★★★★★</div>
                                        <div class="rateit-selected rateit-preset" style="width: 0px; display: block;">
                                            ★★★★★</div>
                                        <div class="rateit-hover" style="width: 0px; display: none;">★★★★★</div>
                                    </div>
                                </div> <span class="danhgia"> <span class="avg-rate">3.5</span> /<span>5</span> của
                                    <span class="count-rate">808</span> đánh giá</span>
                                <script
                                    type="application/ld+json">
                                    {
                                        "@context": "https://schema.org/",
                                        "@type": "AggregateRating",
                                        "ratingValue": "3.5",
                                        "bestRating": "5",
                                        "ratingCount": "808",
                                        "itemReviewed": {
                                            "@type": "CreativeWorkSeries",
                                            "name": "Bạc nhớ lô đề miền Bắc 2025 – Dự đoán số siêu chuẩn"
                                        }
                                    }
                                </script>
                            </div>
                        </div>
                    </div>
                    <h2 class="new-description fulljustify my-3"><strong>Bạc nhớ là phương pháp soi cầu lô đề lâu năm,
                            nổi bật với
                            độ chính xác cao. Các chuyên gia sử dụng xác suất xuất hiện cầu lô từ trước đến nay để chọn
                            ra cầu lô MB
                            đẹp nhất.</strong></h2>
                    <div class="text-center"> <img width="600" height="314"
                            src="<?= $base_url ?>public/media/thumb/Thumb-Cate/bac-nho-600x314.jpg"
                            alt="Bạc nhớ lô đề miền Bắc 2025 – Dự đoán số siêu chuẩn"> </div>
                    <div class="new-content text-justify mt-3">
                        <div class="mb-3 muc-luc py-3">
                            <legend class="font-16 text-mucluc pt-1 pl-4"><i class="fa fa-bars mr-2"></i>Mục lục
                            </legend>
                            <ol class="text-news-link">
                                <li><a rel="nofollow" href="#trick0">Soi cầu bạc nhớ lô đề miền Bắc hôm nay
                                        27/01/2026</a></li>
                                <li><a rel="nofollow" href="#trick1">Kết quả XSMB hôm qua</a></li>
                                <li><a rel="nofollow" href="#trick2">Soi cầu bạc nhớ theo tổng</a></li>
                                <li><a rel="nofollow" href="#trick3">Soi cầu đầu câm</a></li>
                                <li><a rel="nofollow" href="#trick4">Chốt số đuôi câm</a></li>
                                <li><a rel="nofollow" href="#trick5">Bạc nhớ lô đề MB thường đi kèm với nhau</a></li>
                                <li><a rel="nofollow" href="#trick6">Chốt cầu theo thứ</a></li>
                            </ol>
                        </div>
                        <p style="text-align: justify;">Bạc nhớ lô đề là một phương pháp chơi lô đề rất được ưa chuộng,
                            nhưng không
                            phải ai cũng nắm vững cách soi cầu chuẩn xác để mang lại hiệu quả cao. Hôm nay, bạc nhớ MB
                            sẽ cung cấp
                            thống kê chi tiết và giúp anh em tìm ra những lô đề uy tín nhất. Cùng khám phá ngay trong
                            bài viết dưới
                            đây để nâng cao cơ hội chiến thắng!</p>
                        <h3 id="trick0">Soi cầu bạc nhớ lô đề miền Bắc hôm nay 27/01/2026</h3>
                        <p></p>
                        <p class="mb-2">- Hôm qua đề về <b class="text-red">74</b> - Hôm nay nuôi ngay cặp song thủ <b
                                class="text-red">18 - 81</b> chắc chắn trúng</p>
                        <p class="mb-2">- Hôm qua lô có <b class="text-red">74</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">67</b>
                        </p>
                        <p class="mb-2">- Hôm qua lô <b class="text-red">93</b> đã nổ - Hôm nay chắc chắn sẽ có các lô
                            <b class="text-red">70 - 02</b>
                        </p>
                        <p class="mb-2">- Lô <b class="text-red">66</b> đã về hôm qua - Khả năng cao hôm nay sẽ có <b
                                class="text-red">01</b></p>
                        <p class="mb-2">- Kỳ trước về lô <b class="text-red">41</b> - Kỳ quay thường hôm nay cân nhắc
                            cặp <b class="text-red">36 - 45 - 42</b></p>
                        <p class="mb-2">- Kết quả XSMB hôm qua có <b class="text-red">69</b> - Hôm nay đánh cặp <b
                                class="text-red">04 - 80 - 41</b> chắc chắn trúng</p>
                        <p class="mb-2">- Hôm qua có lô <b class="text-red">57</b> nổ - Hôm nay cân nhắc cặp <b
                                class="text-red">53
                                - 33 - 98</b> đẹp nhất</p>
                        <p class="mb-2">- Miền bắc hôm qua về lô <b class="text-red">05</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">94 - 06</b></p>
                        <p class="mb-2">- Lô <b class="text-red">61</b> đã nổ ngày hôm qua - Hôm nay chắc chắn sẽ về lô
                            <b class="text-red">91</b>
                        </p>
                        <p class="mb-2">- Hôm qua xất hiện lô <b class="text-red">82</b> - Hôm nay cân sẽ về <b
                                class="text-red">95
                                - 55 - 96</b></p>
                        <p class="mb-2">- Kỳ trước xuất hiện <b class="text-red">20</b> - Hôm nay đánh cặp <b
                                class="text-red">46 -
                                95</b> cơ hội trúng thưởng cao</p>
                        <p class="mb-2">- Hôm qua lô có <b class="text-red">02</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">17 -
                                52 - 22</b></p>
                        <p class="mb-2">- Kỳ trước về lô <b class="text-red">62</b> - Kỳ quay thường hôm nay cân nhắc
                            cặp <b class="text-red">14 - 49</b></p>
                        <p class="mb-2">- Miền bắc hôm qua về lô <b class="text-red">44</b>- Hôm nay cân nhắc cặp <b
                                class="text-red">94 - 20</b></p>
                        <p class="mb-2">- Miền bắc hôm qua về lô <b class="text-red">81</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">68 - 30 - 50</b></p>
                        <p class="mb-2">- Hôm qua có lô <b class="text-red">85</b> nổ - Hôm nay cân nhắc cặp <b
                                class="text-red">61
                                - 28 - 98</b> đẹp nhất</p>
                        <p class="mb-2">- Miền bắc hôm qua về lô <b class="text-red">13</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">49</b></p>
                        <p class="mb-2">- Hôm qua xất hiện lô <b class="text-red">32</b> - Hôm nay cân sẽ về <b
                                class="text-red">98
                                - 79</b></p>
                        <p class="mb-2">- Kết quả XSMB hôm qua có <b class="text-red">65</b> - Hôm nay đánh cặp <b
                                class="text-red">25</b> chắc chắn trúng</p>
                        <p class="mb-2">- Kỳ trước về <b class="text-red">17</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">96 -
                                44</b></p>
                        <p class="mb-2">- Kỳ trước về lô <b class="text-red">94</b> - Kỳ quay thường hôm nay cân nhắc
                            cặp <b class="text-red">28</b></p>
                        <p class="mb-2">- Kỳ trước xổ số miền Bắc về lô <b class="text-red">39</b> - Kỳ này anh em cân
                            nhắc cặp <b class="text-red">67</b></p>
                        <p class="mb-2">- Kết quả XSMB hôm qua có <b class="text-red">15</b> - Hôm nay đánh cặp <b
                                class="text-red">97</b> chắc chắn trúng</p>
                        <p class="mb-2">- Hôm qua lô có <b class="text-red">67</b> - Hôm nay cân nhắc cặp <b
                                class="text-red">54 -
                                76</b></p>
                        <p class="mb-2">- Kỳ trước về lô <b class="text-red">56</b> - Kỳ quay thường hôm nay cân nhắc
                            cặp <b class="text-red">79 - 59 - 12</b></p>
                        <p class="mb-2">- Kết quả XSMB hôm qua có <b class="text-red">63</b> - Hôm nay đánh cặp <b
                                class="text-red">53 - 24</b> chắc chắn trúng</p>
                        <p></p>
                        <p><span style="color: #ff0000;">»&nbsp;</span><a href="<?= $base_url ?>xs-minh-ngoc-hom-nay.html">Dự đoán
                                xsmb minh ngọc
                            </a></p>
                        <h3 id="trick1">Kết quả XSMB hôm qua</h3>
                        <p></p>
                        <article class="my-2">
                            <div class="result result-single rounded">
                                <div class="bg-red2 text-white text-uppercase px-3 py-2 mb-0 font-weight-bold font-16">
                                    Xổ số Miền
                                    Bắc ngày 26/01/2026 </div>
                                <div class="breadcrumb-table">
                                    <h4 class="breadcrumb-table-title"> <a
                                            href="<?= $base_url ?>xsmb-thu-2.html" title="XSMB thứ 2">XSMB thứ 2</a> / <a
                                            href="<?= $base_url ?>xsmb-26-01-2026.html" title="XSMB 26/01/2026">XSMB
                                            26/01/2026</a> </h4>
                                </div>
                                <div class="table-flex-border">
                                    <table class="table-flex table-result" data-code="XSMB">
                                        <tbody>
                                            <tr>
                                                <td colspan="2">
                                                    <div class="d-flex justify-content-between font-16 p-2"> <span
                                                            class="text-number" nc="5">7UM</span> <span
                                                            class="text-number" nc="5">11UM</span> <span
                                                            class="text-number" nc="5">10UM</span> <span
                                                            class="text-number" nc="5">12UM</span> <span
                                                            class="text-number" nc="5">2UM</span> <span
                                                            class="text-number" nc="5">18UM</span> <span
                                                            class="text-number" nc="5">16UM</span> <span
                                                            class="text-number" nc="5">15UM</span> </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>ĐB</td>
                                                <td> <span class="text-number" nc="5">00974</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G1</td>
                                                <td> <span class="text-number" nc="5">79993</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G2</td>
                                                <td> <span class="text-number" nc="5">49666</span> <span
                                                        class="text-number" nc="5">66441</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G3</td>
                                                <td> <span class="text-number" nc="5">60369</span> <span
                                                        class="text-number" nc="5">22957</span> <span
                                                        class="text-number" nc="5">67805</span> <span
                                                        class="text-number" nc="5">87161</span> <span
                                                        class="text-number" nc="5">45582</span> <span
                                                        class="text-number" nc="5">58420</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G4</td>
                                                <td> <span class="text-number" nc="4">9302</span> <span
                                                        class="text-number" nc="4">9362</span> <span
                                                        class="text-number" nc="4">5044</span> <span
                                                        class="text-number" nc="4">4481</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G5</td>
                                                <td> <span class="text-number" nc="4">2285</span> <span
                                                        class="text-number" nc="4">6013</span> <span
                                                        class="text-number" nc="4">9685</span> <span
                                                        class="text-number" nc="4">3732</span> <span
                                                        class="text-number" nc="4">8265</span> <span
                                                        class="text-number" nc="4">1017</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G6</td>
                                                <td> <span class="text-number" nc="3">294</span> <span
                                                        class="text-number" nc="3">739</span> <span class="text-number"
                                                        nc="3">215</span> </td>
                                            </tr>
                                            <tr>
                                                <td>G7</td>
                                                <td> <span class="text-number" nc="2">85</span> <span
                                                        class="text-number" nc="2">67</span> <span class="text-number"
                                                        nc="2">56</span> <span class="text-number" nc="2">63</span>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="loto loto-single">
                                <table class="table table-bordered table-striped table-xslt-single-col">
                                    <thead>
                                        <tr>
                                            <th>Đầu</th>
                                            <th>Lô tô</th>
                                            <th>Đuôi</th>
                                            <th>Lô tô</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>0</td>
                                            <td> <span>5</span><span>2</span> </td>
                                            <td>0</td>
                                            <td> <span>2</span> </td>
                                        </tr>
                                        <tr>
                                            <td>1</td>
                                            <td> <span>3</span><span>7</span><span>5</span> </td>
                                            <td>1</td>
                                            <td> <span>4</span><span>6</span><span>8</span> </td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td> <span>0</span> </td>
                                            <td>2</td>
                                            <td> <span>8</span><span>0</span><span>6</span><span>3</span> </td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td> <span>2</span><span>9</span> </td>
                                            <td>3</td>
                                            <td> <span>9</span><span>1</span><span>6</span> </td>
                                        </tr>
                                        <tr>
                                            <td>4</td>
                                            <td> <span>1</span><span>4</span> </td>
                                            <td>4</td>
                                            <td> <span>7</span><span>4</span><span>9</span> </td>
                                        </tr>
                                        <tr>
                                            <td>5</td>
                                            <td> <span>7</span><span>6</span> </td>
                                            <td>5</td>
                                            <td>
                                                <span>0</span><span>8</span><span>8</span><span>6</span><span>1</span><span>8</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>6</td>
                                            <td>
                                                <span>6</span><span>9</span><span>1</span><span>2</span><span>5</span><span>7</span><span>3</span>
                                            </td>
                                            <td>6</td>
                                            <td> <span>6</span><span>5</span> </td>
                                        </tr>
                                        <tr>
                                            <td>7</td>
                                            <td> <span>4</span> </td>
                                            <td>7</td>
                                            <td> <span>5</span><span>1</span><span>6</span> </td>
                                        </tr>
                                        <tr>
                                            <td>8</td>
                                            <td> <span>2</span><span>1</span><span>5</span><span>5</span><span>5</span>
                                            </td>
                                            <td>8</td>
                                            <td> </td>
                                        </tr>
                                        <tr>
                                            <td>9</td>
                                            <td> <span>3</span><span>4</span> </td>
                                            <td>9</td>
                                            <td> <span>6</span><span>3</span> </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </article>
                        <p></p>
                        <p><span style="color: #ff0000;">»</span> <a href="<?= $base_url ?>rong-bach-kim-666-hom-nay.html">Rồng
                                Bạch Kim 666</a>
                        </p>
                        <h3 id="trick2">Soi cầu bạc nhớ theo tổng</h3>
                        <p style="text-align: justify;">Soi cầu theo tổng hay theo giải đặc biệt là những phương pháp
                            được rất nhiều
                            anh em tin tưởng lựa chọn. Dưới đây là cách chơi soi cầu theo tổng được các chuyên gia lô đề
                            chia sẻ,
                            giúp anh em nâng cao khả năng trúng số. Cùng tham khảo ngay nhé!</p>
                        <p>- Hôm qua tổng về <span style="color: #ff0000;"><strong>0</strong> </span>- Hôm nay xác suất
                            tổng về
                            <span style="color: #ff0000;"><strong>1</strong> </span>là rất cao
                        </p>
                        <p>- Nếu hôm qua tổng về <strong><span style="color: #ff0000;">1</span> </strong>- Hôm nay chắc
                            chắn tổng sẽ
                            về <strong><span style="color: #ff0000;">7</span></strong></p>
                        <p>- Đề hôm qua về tổng là <strong><span style="color: #ff0000;">2</span> </strong>- Đánh tổng
                            <strong><span style="color: #ff0000;">9</span> </strong>vào ngày kế tiếp
                        </p>
                        <p>- Hôm trước đề về tổng <span style="color: #ff0000;"><strong>3</strong> </span>- Đánh tổng
                            <span style="color: #ff0000;"><strong>0</strong> </span>vào ngày kế tiếp chắc chắn ăn
                        </p>
                        <p>- Tổng hôm nay ra <span style="color: #ff0000;"><strong>4</strong> </span>- Này mai anh em
                            đánh tổng
                            <span style="color: #ff0000;"><strong>3</strong> </span>trúng lớn
                        </p>
                        <p>- Tổng đề hôm qua về <span style="color: #ff0000;"><strong>5</strong> </span>- Hôm nay nuôi
                            ngay tổng
                            <span style="color: #ff0000;"><strong>4</strong></span>
                        </p>
                        <p>- Tổng đề về <span style="color: #ff0000;"><strong>6</strong> </span>- Hôm nay đầu tư tổng
                            <span style="color: #ff0000;"><strong>8</strong> </span>nhé
                        </p>
                        <p>- Tổng đề ra <span style="color: #ff0000;"><strong>7</strong> </span>- Hôm tiếp theo đánh
                            ngay tổng <span style="color: #ff0000;"><strong>2</strong></span></p>
                        <p>- Tổng đề về <span style="color: #ff0000;"><strong>8</strong> </span>- Hôm nay đánh lại tổng
                            <span style="color: #ff0000;"><strong>7</strong></span>
                        </p>
                        <p>- Hôm nay đề về tổng <span style="color: #ff0000;"><strong>9</strong> </span>- Hôm sau chắc
                            chắn nổ tổng
                            <span style="color: #ff0000;"><strong>5</strong><span
                                    style="color: #000000;">.</span></span>
                        </p>
                        <p><span style="color: #ff0000;">»</span> <a href="<?= $base_url ?>soi-cau-3-cang-mien-bac.html">Soi cầu 3
                                càng</a></p>
                        <h3 id="trick3">Soi cầu đầu câm</h3>
                        <p style="text-align: justify;">Thông thường ở mỗi bảng cầu sẽ suất hiện những đầu câm đít câm
                            là những con
                            số không xuất hiện trong ngày. Cùng chúng tôi xem các con số thường đi với đầu câm
                            nhé.&nbsp;</p>
                        <p>- Đầu <span style="color: #ff0000;">0</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">04
                                - 06 - 09</span>.</p>
                        <p>- Đầu<span style="color: #ff0000;"> 1</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">16
                                - 17</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">2</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">21
                                - 25 - 29</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">3</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">30
                                - 36 - 39</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">4</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">40
                                - 44 - 45</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">5</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">54
                                - 59</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">6</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">61
                                - 63</span>.</p>
                        <p>- Đầu<span style="color: #ff0000;"> 7</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">70
                                - 71 - 73 - 75</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">8</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">80
                                - 82 - 89</span>.</p>
                        <p>- Đầu <span style="color: #ff0000;">9</span> câm chắc chắn hôm sau sẽ ra <span
                                style="color: #ff0000;">95
                                - 92</span>.</p>
                        <p><span style="color: #ff0000;">»</span> <a href="<?= $base_url ?>soi-cau-doc-thu-de.html">Độc thủ đề</a>
                        </p>
                        <h3 id="trick4">Chốt số đuôi câm</h3>
                        <p style="text-align: justify;">Tương tự với cách chơi bạc nhớ đầu câm ở phía trên, nếu như xuất
                            hiện đuôi
                            câm ở giải kết quả XSMB ngày hôm nay thì cũng sẽ có rất nhiều con số may mắn có xác suất ra
                            cao ở ngày
                            tiếp theo. Dưới đây là những con số mà chúng tôi muốn đưa ra để anh em tham khảo.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">0</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">00 - 20 - 80</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">1</span> câm thì ngày hôm sau thường sẽ ra<span
                                style="color: #ff0000;"> 21 - 41</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">2</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">22 - 52 - 82</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">3</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">73 - 83</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">4</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">64 - 84</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">5</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">55 - 85 - 95</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">6</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">06 - 16 - 56</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">7</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">17 - 47 - 67</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">8</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">08 - 18 - 88</span>.</p>
                        <p>- Đuôi (đít) <span style="color: #ff0000;">9</span> câm thì ngày hôm sau thường sẽ ra <span
                                style="color: #ff0000;">29 - 39 - 59 - 99</span>.</p>
                        <h3 id="trick5">Bạc nhớ lô đề MB thường đi kèm với nhau</h3>
                        <p>- Cặp lô <span style="color: #ff0000;">37 - 73</span> thường sẽ đi kèm với lô <span
                                style="color: #ff0000;">10 - 01</span>.</p>
                        <p>- Nếu lô <span style="color: #ff0000;">25</span> hoặc <span style="color: #ff0000;">52</span>
                            thường sẽ
                            về <span style="color: #ff0000;">22</span>.</p>
                        <p>- Lô <span style="color: #ff0000;">76</span> thường trong ngày sẽ về cùng <span
                                style="color: #ff0000;">47</span>.</p>
                        <p>- Lô <span style="color: #ff0000;">11</span> thường sẽ đi kèm với <span
                                style="color: #ff0000;">44</span>.</p>
                        <p>- Lô <span style="color: #ff0000;">66</span> thường sẽ về cùng lô <span
                                style="color: #ff0000;">33</span>.</p>
                        <p>- Cặp lô kép <span style="color: #ff0000;">77 - 44</span> thường đi kèm với <span
                                style="color: #ff0000;">55</span>.</p>
                        <p>- Lô <span style="color: #ff0000;">77</span> hay đi kèm với lô <span
                                style="color: #ff0000;">44</span>.
                        </p>
                        <p>- Lô <span style="color: #ff0000;">49</span> thường trong ngày sẽ về cùng <span
                                style="color: #ff0000;">23</span>.</p>
                        <h3 id="trick6">Chốt cầu theo thứ</h3>
                        <p>- Các ngày thứ 5, thứ 7 thường sẽ về lô <span style="color: #ff0000;">97</span></p>
                        <p>- Các ngày thứ 7, chủ nhật, thứ 2, thứ 3 thường sẽ về cặp kép <span
                                style="color: #ff0000;">33</span></p>
                        <p>- Ngày thứ 7 và chủ nhật sẽ hay xuất hiện cặp lô <span style="color: #ff0000;">89 -</span>
                            <span style="color: #ff0000;">98</span>
                        </p>
                        <p>- Ngày thứ 5 và chủ nhật thường hay xuất hiện lô <span style="color: #ff0000;">56</span></p>
                        <p>- Các ngày thứ 4, thứ 5, thứ 6 hay về lô kép <span style="color: #ff0000;">66</span>.</p>
                        <p style="text-align: justify;">Trên đây là những cầu bạc nhớ Rồng Bạch Kim mà <a
                                href="<?= $base_url ?>">Soi cầu 247</a>
                            muốn mang đến cho anh em. Hy vọng anh em có thể chốt số may mắn nhất. Chúc anh em thắng lớn.
                        </p>
                    </div>
                </div>
                <div class="my-3">
                    <h3 class="title-bg-blue border-radius-top">Các phương pháp soi cầu khác</h3>
                    <div class="border border-radius-bottom px-3 pb-3">
                        <ul class="style-list-star-red">
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>rong-bach-kim.html"
                                    title="Rồng Bạch Kim 247">Rồng
                                    Bạch Kim 247</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>bach-thu-de-xsmb-hom-nay.html"
                                    title="Độc thủ đề - Bạch thủ de hôm nay">Độc thủ đề - Bạch thủ de hôm nay</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-24h-du-doan-xo-so-24h-mien-bac.html"
                                    title="Soi cầu 24h đẹp bất bại hôm nay!">Soi cầu 24h đẹp bất bại hôm nay!</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>soi-cau-mien-phi-888.html"
                                    title="Soi cầu 888 Vip 2 nháy MB siêu đẹp">Soi cầu 888 Vip 2 nháy MB siêu đẹp</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-7777-soi-cau-chuan-nhat.html"
                                    title="Soi cầu 7777 chốt số miền Bắc siêu chuẩn">Soi cầu 7777 chốt số miền Bắc siêu
                                    chuẩn</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>soi-cau-666-xsmb.html"
                                    title="Soi cầu 666 chốt số hàng ngày miễn phí">Soi cầu 666 chốt số hàng ngày miễn
                                    phí</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>soi-cau-366-mb.html"
                                    title="Soi cầu 366 miền Bắc bất bại">Soi cầu 366 miền Bắc bất bại</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>soi-cau-3-cang-mien-bac.html"
                                    title="Soi cầu 3 càng chính xác nhất">Soi cầu 3 càng chính xác nhất</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-xsmb-win2888-asia.html"
                                    title="Soi cầu XSMB Win2888 asia chính xác 100%">Soi cầu XSMB Win2888 asia chính xác
                                    100%</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-xsmb-vip-hom-nay.html"
                                    title="Soi cầu lô VIP miền Bắc đẹp nhất">Soi cầu lô VIP miền Bắc đẹp nhất</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-wap-du-doan-xsmb-wap-hom-nay-chinh-xac-nhat.html"
                                    title="Soi cầu Wap 3 miền cực chuẩn">Soi cầu Wap 3 miền cực chuẩn</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-3-mien-du-doan-xo-so-3-mien.html"
                                    title="Soi cầu 3 miền miễn phí chính xác">Soi cầu 3 miền miễn phí chính xác</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-du-doan-xsmb-chinh-xac-100.html"
                                    title="Soi cầu dự đoán XSMB chính xác 100">Soi cầu dự đoán XSMB chính xác 100</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-lo-chinh-xac-nhat-mien-bac.html"
                                    title="Soi cầu lô chính xác nhất miền Bắc">Soi cầu lô chính xác nhất miền Bắc</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>nuoi-lo-khung-xsmb.html"
                                    title="Nuôi lô khung 1, 2, 3, 5 ngày siêu chuẩn xác">Nuôi lô khung 1, 2, 3, 5 ngày
                                    siêu chuẩn
                                    xác</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>soi-cau-lo-de-chuan-xsmb.html"
                                    title="Soi cầu lô de chuẩn chính xác nhất">Soi cầu lô de chuẩn chính xác nhất</a>
                            </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a
                                    href="<?= $base_url ?>dan-de-36-so-khung-3-ngay.html"
                                    title="Dàn đề 36 số bất bại ăn liên tục">Dàn đề 36 số bất bại ăn liên tục</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>lo-top.html"
                                    title="Lô Top miền Bắc đẹp nhất ngày hôm nay">Lô Top miền Bắc đẹp nhất ngày hôm
                                    nay</a> </li>
                            <li class="lh-18px my-3 font-weight-bold"> <a href="<?= $base_url ?>bac-nho-lo-de-xsmb.html"
                                    title="Bạc nhớ lô đề miền Bắc 2025">Bạc nhớ lô đề miền Bắc 2025</a> </li>
                        </ul>
                    </div>
                </div>
            </div>

            <!-- SIDEBAR LEFT (col-xl-200) -->
            <div class="col-xl-200 mx-lg-3 mx-lg-0 pr-md-3 pr-lg-0 order-2 order-lg-1 font-14">
                <?php $this->partial('partials/sidebar_left'); ?>
            </div>

            <!-- SIDEBAR RIGHT (col-xl-300) -->
            <div class="col-xl-300 mt-3 mt-md-0 order-1 order-lg-2">
                <?php $this->partial('partials/sidebar_right'); ?>
            </div>
        </div>
    </div>
</main>

<style>
    #trick1,
    #trick2,
    #trick3,
    #trick4,
    #trick5,
    #trick6,
    #trick7,
    #trick8,
    #trick9,
    #trick10 {
        margin-top: 10px;
    }
</style>