<main class="container-fluid mt-3 px-0 px-md-3 clearfix">
    <div class="row g-0 g-md-3">
        <div class="col-12 col-lg-8">
            <article class="the__article mb-4">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb clearfix">
                        <li class="breadcrumb-item"><a title="Trang chủ" href="/"><span>Trang
                                    chủ</span></a></li>
                        <li class="breadcrumb-item"><span>Ý nghĩa các con số</span></li>
                    </ol>
                </nav>
                <h1 class="fs-3 mt-2">Ý nghĩa các con số từ 00 đến 99 trong lô đề</h1>
                <div class="article__content mt-4">
                    <p>Trước năm 1954, ở Sài Gòn - Chợ Lớn, có hai chỗ đánh bạc rất nổi tiếng, đó là các sòng
                        Kim Chung và sòng Đại Thế Giới.</p>
                    <p>Trong số các trò chơi cờ bạc đó, có một trò gọi là Xổ số đề, tức là xổ các cặp số đã được
                        đề trên các tấm vé.</p>
                    <p>Mỗi vé có hai con số, từ 00 đến 99. Cứ sau khi bán hết một đợt vé người ta lại "xổ", tức
                        bắt thăm xem vé nào trúng. Nếu trúng thì một đồng ăn bảy mươi đồng.</p>
                    <p>Như vậy là Ban tổ chức (Thầu) được lời 30% mỗi lần xổ, bởi từ 00 đến 99 có 100 vé. Giả sử
                        mỗi vé ghi giá 1 đồng thì thu được 100 đồng, thì Thầu chỉ phải trả có 70 đồng mà thôi,
                        tức là còn lời được 30 đồng (một con số rất lớn khó tưởng tượng nổi! Lời 30%!).</p>
                    <p>Khi thông báo số trúng, để tăng thêm phần hấp dẫn, người ta treo những tấm bảng thật lớn
                        đã cuộn tròn sẵn giống như những cuộn lịch, treo thật cao trên các cây cột, ai ai cũng
                        nhìn thấy.</p>
                    <p>Bốc thăm trước mặt một số người làm nhân chứng xong, xổ ra số 35 trúng chẳng hạn, họ hô
                        lên trên loa bằng cả tiếng Tàu lẫn tiếng Việt: "Xập Xám Ửng... Ba Mươi Lăm...". Lúc đó,
                        một người ở trên cao dùng kéo cắt hoặt đốt sợi dây cột tấm bảng mang số 35 đã cuộn được
                        xổ xuống, dưới hai con số đó có kèm theo hình vẽ một con dê đực, hai sừng cong lên cùng
                        với chòm râu dê!</p>
                    <p><img style="display: inline-block; margin: 0; box-shadow: none;"
                            src="images/images950785_12congiap_amlich.jpg"></p>
                    <p>Vì sao có hình vẽ con dê? Người ta lý luận rằng vì người Hoa thời đó ít người đọc được
                        các con số dùng trong tiếng Việt, mà dân cờ bạc người Việt cũng có nhiều người dốt, chữ
                        cắn làm đôi cũng không biết. Do vậy người ta cẩn thận kèm theo mỗi con số là một hình
                        vẽ, để ai muốn coi số cũng được mà coi hình cũng được.</p>
                    <p>Ví dụ: số 35 họ vẽ con dê, số 09 họ vẽ con cá lớn, số 11 họ vẽ con cá nhỏ, số 14 vẽ con
                        chó, số 16 vẽ con bướm, v.v...</p>
                    <p>Trong các chiếc vé cũng vẽ như vậy. Đây chỉ là những hình vẽ vô tình, dùng riết thành
                        quen vậy thôi, chứ giữa con số 35 và con dê không có liên quan gì đến nhau cả.</p>
                    <p>Vào thời ấy sự gán các con số cho con vật trên tờ vé như sau (Lưu ý rẳng có 40 hình vẽ
                        đại diện, sau đó lại trở lại con vật cũ nhưng với hình vẽ lớn hơn.)</p>
                    <p>00 : trứng vịt<br>01 - 41 - 81 : con cá trắng<br>02 - 42 - 82 : ốc<br>03 - 43 - 83 : xác
                        chết (con vịt)<br>04 - 44 - 84 : con công<br>05 - 45 - 85 : con trùng<br>06 - 46 - 86 :
                        con cọp<br>07 - 47 - 87 : con heo<br>08 - 48 - 88 : con thỏ<br>09 - 49 - 89 : con
                        trâu<br>10 - 50 - 90 : con rồng nằm<br>11 - 51 - 91 : con chó<br>12 - 52 - 92 : con
                        ngựa<br>13 - 53 - 93 : con voi<br>14 - 54 - 94 : con mèo nhà<br>15 - 55 - 95 : con
                        chuột<br>16 - 56 - 96 : con ong<br>17 - 57 - 97 : con hạc<br>18 - 58 - 98 : con mèo
                        rừng<br>19 - 59 - 99 : con bướm<br>20 - 60 : con rết (con rít)<br>21 - 61 : cô gái (có
                        khi người ta gọi trại ra là con đĩ, do hình vẽ tả cô gái lả lơi)<br>22 - 62 : bồ câu
                        <br>23 - 63 : con khỉ <br>24 - 64 : con ếch<br>25 - 65 : con ó<br>26 - 66 : rồng
                        bay<br>27 - 67 : con rùa<br>28 - 68 : con gà<br>29 - 69 : con lươn<br>30 - 70 : con cá
                        đen<br>31 - 71 : con tôm<br>32 - 72 : con rắn<br>33 - 73 : con nhện<br>34 - 74 : con
                        nai<br>35 - 75 : con dê<br>36 - 76 : bà vải<br>37 - 77 : ông trời<br>38 - 78 : ông
                        địa<br>39 - 79 : thần tài<br>40 - 80 : ông táo
                    </p><br>
                </div>
            </article>
            <div class="bg-white border mb-3 rounded shadow-sm">
                <div class="box__title">Các bài viết liên quan</div>
                <ul class="list__links">
                    <li><a href="/lich-mo-thuong-xo-so-kien-thiet-toan-quoc">Lịch xổ số 3 miền toàn quốc
                        </a></li>
                    <li><a href="/co-cau-giai-thuong-xo-so-kien-thiet-toan-quoc">Cơ cấu giải thưởng xổ số 3
                            miền </a></li>
                </ul>
            </div>
            <div class="box mx-md-0">
                <div class="box__title"><a class="text-body text-decoration-none"
                        href="du-doan-xo-so-soi-cau">Dự đoán xổ số hôm nay</a></div>
                <ul class="list__articles grid d-flex align-items-start flex-wrap p-2">
                    <li class="p-2 d-block first">
                        <figure class="article__thumb__grid mb-2"><a class="p-0"
                                href="/du-doan-xsmn-20-7-2025-soi-cau-xo-so-mien-nam-20-07-2025"
                                title="Soi cầu dự đoán xổ số Miền Nam ngày 20-07-2025"><img
                                    class="lozad rounded" alt="Soi cầu dự đoán xổ số Miền Nam ngày 20-07-2025"
                                    src="images/ajax-loader.gif"
                                    data-src="medias/images/thumbs/450x300/2024/08/07/du-doan-xsmn_1723021048.jpg"></a>
                        </figure>
                        <aside><a class="d-block fs-7 text-uppercase mb-1 text-red" href="/du-doan-xsmn"
                                title="Dự đoán xổ số Miền Nam">Dự đoán XSMN</a><a
                                class="d-block text-decoration-none"
                                href="/du-doan-xsmn-20-7-2025-soi-cau-xo-so-mien-nam-20-07-2025"
                                title="Soi cầu dự đoán xổ số Miền Nam ngày 20-07-2025"><span>Dự đoán XSMN
                                    20/7/2025, soi cầu Xổ Số Miền Nam 20-07-2025</span></a></aside>
                    </li>
                    <li class="p-2 d-block ">
                        <figure class="article__thumb__grid mb-2"><a class="p-0"
                                href="/du-doan-xsmt-20-7-2025-soi-cau-xo-so-mien-trung-20-07-2025"
                                title="Soi cầu dự đoán xổ số Miền Trung ngày 20-07-2025"><img
                                    class="lozad rounded" alt="Soi cầu dự đoán xổ số Miền Trung ngày 20-07-2025"
                                    src="images/ajax-loader.gif"
                                    data-src="medias/images/thumbs/450x300/2024/08/07/du-doan-xsmt_1723020354.jpg"></a>
                        </figure>
                        <aside><a class="d-block fs-7 text-uppercase mb-1 text-red" href="/du-doan-xsmt"
                                title="Dự đoán xổ số Miền Trung">Dự đoán XSMT</a><a
                                class="d-block text-decoration-none"
                                href="/du-doan-xsmt-20-7-2025-soi-cau-xo-so-mien-trung-20-07-2025"
                                title="Soi cầu dự đoán xổ số Miền Trung ngày 20-07-2025"><span>Dự đoán XSMT
                                    20/7/2025, soi cầu Xổ Số Miền Trung 20-07-2025</span></a></aside>
                    </li>
                    <li class="p-2 d-block ">
                        <figure class="article__thumb__grid mb-2"><a class="p-0"
                                href="/du-doan-xsmb-20-7-2025-soi-cau-xo-so-mien-bac-20-07-2025"
                                title="Soi cầu dự đoán xổ số Miền Bắc ngày 20-07-2025"><img
                                    class="lozad rounded" alt="Soi cầu dự đoán xổ số Miền Bắc ngày 20-07-2025"
                                    src="images/ajax-loader.gif"
                                    data-src="medias/images/thumbs/450x300/2024/08/07/du-doan-xsmb_1723020248.jpg"></a>
                        </figure>
                        <aside><a class="d-block fs-7 text-uppercase mb-1 text-red" href="/du-doan-xsmb"
                                title="Dự đoán xổ số Miền Bắc">Dự đoán XSMB</a><a
                                class="d-block text-decoration-none"
                                href="/du-doan-xsmb-20-7-2025-soi-cau-xo-so-mien-bac-20-07-2025"
                                title="Soi cầu dự đoán xổ số Miền Bắc ngày 20-07-2025"><span>Dự đoán XSMB
                                    20/7/2025, soi cầu Xổ Số Miền Bắc 20-07-2025</span></a></aside>
                    </li>
                </ul>
            </div>
        </div>
        <?php $this->partial('layouts/rightbar'); ?>
    </div>
</main>