<?php
/**
 * Partial: Nội dung giới thiệu về XSMB
 */
?>

<div class="article__content p-3 bg-white shadow-sm mt-5 rounded js-bottom-content">
    <p>
        Để thuận tiện tham gia dự thưởng Miền Bắc, mời các bạn tham khảo lịch quay sau đây:
    </p>
    
    <h3><strong>Lịch mở thưởng <a title="xổ số Miền Bắc" href="/ket-qua-xsmb-xo-so-kien-thiet-mien-bac-sxmb-kqxsmb.html">xổ số Miền Bắc</a></strong></h3>
    
    <p><a title="XSMB Thứ 2" href="/xsmb-thu-2-ket-qua-xo-so-mien-bac.html">XSMB Thứ 2</a>: xổ số Thủ Đô Hà Nội</p>
    <p><a title="XSMB Thứ 3" href="/xsmb-thu-3-ket-qua-xo-so-mien-bac.html">XSMB Thứ 3</a>: xổ số Quảng Ninh</p>
    <p><a title="XSMB Thứ 4" href="/xsmb-thu-4-ket-qua-xo-so-mien-bac.html">XSMB Thứ 4</a>: xổ số Bắc Ninh</p>
    <p><a title="XSMB Thứ 5" href="/xsmb-thu-5-ket-qua-xo-so-mien-bac.html">XSMB Thứ 5</a>: xổ số Thủ Đô Hà Nội</p>
    <p><a title="XSMB Thứ 6" href="/xsmb-thu-6-ket-qua-xo-so-mien-bac.html">XSMB Thứ 6</a>: xổ số Hải Phòng</p>
    <p><a title="XSMB Thứ 7" href="/xsmb-thu-7-ket-qua-xo-so-mien-bac.html">XSMB Thứ 7</a>: xổ số Nam Định</p>
    <p><a title="XSMB Chủ Nhật" href="/xsmb-chu-nhat-ket-qua-xo-so-mien-bac.html">XSMB Chủ Nhật</a>: xổ số Thái Bình</p>
    
    <p>Khi may mắn trúng giải thưởng của Xổ số Miền Bắc, mời quý khách vui lòng liên hệ với các công ty phát hành vé số để nhận giải thưởng. Chi tiết liên hệ các công ty phát hành vé số Xổ số Miền Bắc:</p>
    
    <h4 class="font-15 font-weight-bold pb-2">Xổ số kiến thiết Hà Nội</h4>
    <p>Công ty TNHH Một thành viên Xổ số kiến thiết Thủ đô</p>
    <p>Địa chỉ: 53E - Hàng Bài - Hoàn Kiếm - Hà Nội</p>
    <p>Điện thoại: 04.9433636 - Fax: 04.9438874 - Đường dây nóng: 04.9439928, 04.9433123</p>
    
    <h4 class="font-15 font-weight-bold pb-2">Xổ số kiến thiết Quảng Ninh</h4>
    <p>CÔNG TY TNHH MTV Xổ số kiến thiết Quảng Ninh</p>
    <p>Trụ sở chính: Số 2 - phố Kim Hoàn - phường Bạch Đằng - TP Hạ Long - Tỉnh Quảng Ninh</p>
    <p>Điện thoại: 0333.825.355 * Fax: 0333.829.723 * Email: xsktqn@vnn.vn</p>
    
    <h4 class="font-15 font-weight-bold pb-2">Xổ số kiến thiết Bắc Ninh</h4>
    <p>CÔNG TY TNHH MTV xổ số kiến thiết Bắc Ninh</p>
    <p>Địa chỉ: Số 27 Đ.Nguyễn Đăng Đạo, P.Suối Hoa, TP.Bắc Ninh, T.Bắc Ninh</p>
    <p>Điện thoại: 0222.3821.256 - Fax: 0222.3822.748</p>
    
    <h4 class="font-15 font-weight-bold pb-2">Xổ số kiến thiết Hải Phòng</h4>
    <p>Công Ty Trách Nhiệm Hữu Hạn Một Thành Viên Xổ Số Hải Phòng</p>
    <p>Địa chỉ: Số 19 Điện Biên Phủ - Phường Máy Tơ - Quận Ngô Quyền - Hải Phòng</p>
    <p>Điện thoại: 0313551243 - Fax: 0313836139</p>
    
    <h4 class="font-15 font-weight-bold pb-2">Xổ số kiến thiết Nam Định</h4>
    <p>CÔNG TY TNHH MTV Xổ số kiến thiết Nam Định</p>
    <p>Địa chỉ: 157 Trần Hưng Đạo - Thành phố Nam Định.</p>
    <p>Điện thoại: 228.3849241 - Fax: 228.3844377</p>
    <p>Email: xskt@namdinh.gov.vn</p>
    
    <h4 class="font-15 font-weight-bold pb-2">Xổ số kiến thiết Thái Bình</h4>
    <p>Công ty TNHH một thành viên xổ số kiến thiết Thái Bình</p>
    <p>Số 03 - Phố Quang Trung, Phường Quang Trung, Thành Phố Thái Bình, tỉnh Thái Bình</p>
    <p>Điện thoại : (0363).831.731 - Fax: (0363).833.029</p>
    
    <h3 style="text-align: justify;"><span style="font-size: 12pt;">Cơ cấu giải thưởng XSMB mới nhất</span></h3>
    <p style="text-align: justify;">Mỗi tờ vé số miền Bắc trị giá 10.000 đồng và có 81.150 giải thưởng với giá trị như sau:</p>
    
    <p style="text-align: justify;">- 03 giải đặc biệt với 1 lần quay trùng 5 chữ số, giá trị mỗi giải đặc biệt là 1 tỷ đồng, tổng giá trị giải thưởng của 3 giải lên đến 3 tỷ đồng.</p>
    
    <p style="text-align: justify;">- Có 15 giải nhất với 1 lần quay thưởng, gồm có 5 số, giá trị mỗi giải là 10 triệu đồng, tổng giá trị 15 giải nhất lên đến 150 triệu đồng.</p>
    
    <p style="text-align: justify;">- Có 30 giải nhì với 2 lần quay thưởng, gồm 5 chữ số, giá trị mỗi giải là 5 triệu đồng, tổng giá trị 30 giải nhì là 150 triệu đồng.</p>
    
    <p style="text-align: justify;">- Có 90 giải ba với 6 lần quay, gồm có 5 chữ số, giá trị mỗi giải ba là 1 triệu đồng.</p>
    
    <p style="text-align: justify;">- 600 giải tư với 4 lần quay, gồm có 4 chữ số, giá trị mỗi giải tư là 400 nghìn đồng.</p>
    
    <p style="text-align: justify;">- 900 giải năm với 6 lần quay, gồm có 4 chữ số, giá trị mỗi giải nhận được 200 nghìn đồng. 4500 giải sáu với 3 lần quay, gồm 3 chữ số, trị giá mỗi giải là 100 nghìn đồng.</p>
    
    <p style="text-align: justify;">- 60.000 giải bảy với 4 lần quay, gồm có 2 chữ số, mỗi giải nhận được 40 nghìn đồng.</p>
    
    <p style="text-align: justify;">- 12 giải phụ đặc biệt dành cho những tấm vé may mắn trùng số với giải ĐB nhưng khác ký hiệu, nhận thưởng mỗi giải 20 triệu đồng.</p>
    
    <p style="text-align: justify;">- 15.000 giải khuyến khích dành cho tờ vé số trùng 2 chữ số hàng đơn vị và hàng trục với giải đặc biệt, sẽ nhận được phần thưởng trị giá 40 nghìn đồng.</p>
    
    <h3 style="text-align: justify;"><span style="font-size: 12pt;">Cách thức nhận giải khi trúng thưởng xổ số miền Bắc</span></h3>
    <p style="text-align: justify;">Khi may mắn trúng thưởng bất kỳ giải nào của XSMB, anh em cần liên hệ ngay với công ty xổ số kiến thiết miền Bắc hoặc các đại lý được in sau tờ vé số để được hướng dẫn nhận thưởng.</p>
    
    <p style="text-align: justify;">Tờ vé số nhận giải phải trùng khớp các số khi quay thưởng, khớp ngày quay thưởng và phải còn nguyên vẹn, không bị rách nát hay tẩy xóa, chắp vá. Thời gian nhận thưởng xổ số miền bắc là tối đa 30 ngày kể từ ngày công bố giải thưởng.</p>
    
    <p style="text-align: justify;">Để dò vé số miền Bắc nhanh chóng anh em có thể theo dõi chương trình quay thưởng trên tivi, đài VOV hoặc xem trực tiếp tại <a href="/" title="chuyên trang Soi cầu 247">chuyên trang Soi cầu 247</a> của chúng tôi. Cam kết cập nhật kết quả xổ số nhanh chóng nhất tới anh em. Chúc anh em may mắn!</p>
</div>

