<main>
    <div class="container">
        <div class="row">
            <div class="col-xl-610">
                <div class="bg-white border-radius-4 py-3">
                    <h1 class="font-20"><strong>Tổng hợp các cặp lô hay đi cùng nhau về nhiều nhất</strong></h1>
                    <div class="d-flex font-13 justify-content-between my-3 flex-wrap">
                        <div class="text-gray">
                            <div class="new-date">Thứ Hai, 14/09/2020 - 13:20</div>
                            <div class="allRate"> <input type="range" value="0" step="0.25" id="backing5"> <input
                                    type="text" value="news/371" hidden id="voteLink">
                                <div class="rateit" data-rateit-backingfld="#backing5" data-rateit-resetable="false"
                                    data-rateit-ispreset="true" data-rateit-min="0" data-rateit-max="5"
                                    data-rateit-mode="font" data-rateit-icon="" style="font-family:fontawesome"> </div>
                                <span class="danhgia"> <span class="avg-rate">5</span> /<span>5</span> của <span
                                        class="count-rate">1</span> đánh giá</span>
                                <script type="application/ld+json">
                                    {
                                        "@context": "https://schema.org/",
                                        "@type": "AggregateRating",
                                        "ratingValue": "5",
                                        "bestRating": "5",
                                        "ratingCount": "1",
                                        "itemReviewed": {
                                            "@type": "CreativeWorkSeries",
                                            "name": "Tổng hợp các cặp lô hay đi cùng nhau về nhiều nhất"
                                        }
                                    }
                                </script>
                            </div>
                        </div>
                        <div class="new-category"> <span><i class="icon-circle text-red font-6 align-middle"
                                    aria-hidden="true"></i></span> <a
                                href="/bi-kip-ve-phuong-phap-soi-cau-lo-de-chuan-c110.html" title="Bi kíp chơi lô đề">Bi
                                kíp chơi lô đề</a> </div>
                    </div>
                    <h2 class="new-description font-weight-bold"> Để chọn được những con số đẹp, cặp lô hay đi cùng nhau
                        thì anh em cần phải sử dụng nhiều phương pháp, thống kê, soi cầu khác nhau. Bài viết này chúng
                        tôi chia sẻ với anh em thống kê các cặp lô hay đi cùng nhau trong bảng kết quả xổ số. </h2>
                    <div class="other_post p-3">
                        <ul class="other_post_list">
                            <li class="other_post_item text-news-link"> <i class="icon-circle font-5 align-middle"></i>
                                <a class="font-14" href="/cac-phuong-phap-soi-cau-song-thu-lo-hieu-qua-nhat-d75.html"
                                    title="Các phương pháp soi cầu song thủ lô hiệu quả nhất"> Phương pháp soi cầu song
                                    thủ lô hiệu quả nhất </a>
                            </li>
                            <li class="other_post_item text-news-link"> <i class="icon-circle font-5 align-middle"></i>
                                <a class="font-14" href="/phuong-phap-soi-cau-bac-nho-d96.html"
                                    title="Soi cầu bạc nhớ - Cách soi cầu bạc nhớ bách phát bách trúng"> Soi cầu bạc nhớ
                                    - Phương pháp soi cầu bạc nhớ 2022 siêu chuẩn </a>
                            </li>
                            <li class="other_post_item text-news-link"> <i class="icon-circle font-5 align-middle"></i>
                                <a class="font-14" href="/cach-soi-cau-lo-bang-phuong-phap-kim-kep-chuan-100-d236.html"
                                    title="Cách soi cầu lô bằng phương pháp kìm kẹp chuẩn 100%"> Cách soi cầu lô bằng
                                    phương pháp kìm kẹp chuẩn 100% </a>
                            </li>
                        </ul>
                    </div>
                    <div class="text-center my-2" id="news-thumbnail"> <img loading="lazy" width="600" height="314"
                            alt="Tổng hợp các cặp lô hay đi cùng nhau về nhiều nhất"
                            src="/media/thumb/kinh-nghiem-lo-de/cac-cap-lo-hay-di-cung-nhau--1--600x314.jpg"> </div>
                    <div class="new-content text-justify">
                        <div class="mb-3 muc-luc py-3">
                            <legend class="font-16 text-mucluc pt-1 pl-4"><i class="fa fa-bars mr-2"></i>Mục lục
                            </legend>
                            <ol class="text-news-link">
                                <li><a rel="nofollow" href="#trick0">Các con lô hay đi cùng nhau</a></li>
                                <li><a rel="nofollow" href="#trick1">Các cặp lô hay về theo đôi</a></li>
                                <li><a rel="nofollow" href="#trick2">Những cặp lô hay về theo các thứ trong tuần</a>
                                </li>
                                <li><a rel="nofollow" href="#trick3">Những con lô hay đi cùng với giải đặc biệt</a></li>
                                <li><a rel="nofollow" href="#trick4">3 cặp số hay đi kèm nhau về nhiều nhất</a></li>
                            </ol>
                        </div>
                        <p style="text-align: justify;">Đối với anh em chơi lô đề, ai cũng biết rằng đoán trúng con lô
                            hay đề về trong ngày là điều khá khó khăn.Trong đó, có những con lô không về đơn lẻ mà còn
                            có những quy luật và hay về cả cặp cùng nhau. Mỗi con lô về thường có những quy luật riêng.
                            Có nhiều cách để anh em có thể xác định được những cặp lô hay đi cùng nhau. Dựa vào những
                            kinh nghiệm của các tay chơi lão luyện, áp dụng những phương pháp soi cầu lô, thống kê,...
                            <a href="/">Soi cầu 247</a> đã tổng hợp <a
                                href="/tong-hop-cac-cap-lo-hay-di-cung-nhau-d371.html">các cặp lô hay đi cùng nhau
                            </a>trong bài viết này để đem lại may mắn cho anh em.
                        </p>
                        <h3 id="trick0" style="text-align: justify;">Các con lô hay đi cùng nhau</h3>
                        <ul>
                            <li style="text-align: justify;">Hôm trước về con <span style="color: #ff0000;">17</span>
                                thì hôm sau anh em đánh con <span style="color: #ff0000;">48</span></li>
                            <li style="text-align: justify;">Hôm trước ra con <span style="color: #ff0000;">25</span>
                                thì hôm sau nuôi con <span style="color: #ff0000;">45</span></li>
                            <li style="text-align: justify;">Hôm trước về con lô <span style="color: #ff0000;">67</span>
                                thì hôm sau nuôi con <span style="color: #ff0000;">79</span></li>
                            <li style="text-align: justify;">Hôm trước về số <span style="color: #ff0000;">69</span> thì
                                hôm sau đừng bỏ qua con<span style="color: #ff0000;"> 80</span></li>
                            <li style="text-align: justify;">Nếu hôm trước về con <span
                                    style="color: #ff0000;">49</span> thì hôm sau đánh <span
                                    style="color: #ff0000;">23</span></li>
                            <li style="text-align: justify;">Hôm trước kết quả về <span
                                    style="color: #ff0000;">59</span> thì hôm sau đánh con <span
                                    style="color: #ff0000;">98</span></li>
                            <li style="text-align: justify;">Hôm trước nổ con <span style="color: #ff0000;">75</span>
                                thì hôm sau con <span style="color: #ff0000;">35</span> có khả năng về</li>
                            <li style="text-align: justify;">Hôm qua ra con <span style="color: #ff0000;">00</span> thì
                                hôm nay đánh con <span style="color: #ff0000;">99</span></li>
                            <li style="text-align: justify;">Thấy con <span style="color: #ff0000;">99</span> về hôm nay
                                thì hôm sau nuôi số <span style="color: #ff0000;">22</span></li>
                            <li style="text-align: justify;">Lô về <span style="color: #ff0000;">02</span> thì hôm sau
                                đánh con <span style="color: #ff0000;">22</span></li>
                            <li style="text-align: justify;">Hôm trước nổ con <span style="color: #ff0000;">13</span>
                                thì hôm sau về con<span style="color: #ff0000;"> 22</span></li>
                            <li style="text-align: justify;">Hôm trước về con <span style="color: #ff0000;">66</span>
                                thì hôm sau nuôi con <span style="color: #ff0000;">11</span></li>
                        </ul>
                        <p style="text-align: center;"><strong><span style="color: #ff0000;"></span></strong></p>
                        <p style="text-align: center;"><strong><span style="color: #ff0000;">» <a
                                        href="/ket-qua-xsmb-xo-so-kien-thiet-mien-bac-sxmb-kqxsmb.html">KQXSMB</a> «</span></strong>
                        </p>
                        <p><span style="color: #ff0000;"><img src="/media/kinh-nghiem-lo-de/cap-lo-hay-di-cung-nhau.jpg"
                                    alt="cac cap lo hay di cung nhau" width="600" height="450"
                                    style="display: block; margin-left: auto; margin-right: auto;"></span></p>
                        <h3 id="trick1" style="text-align: justify;">Các cặp lô hay về theo đôi</h3>
                        <ul>
                            <li style="text-align: justify;">Hôm trước về cặp <span style="color: #ff0000;">01 -
                                    10</span> thì hôm sau nên đánh cặp <span style="color: #ff0000;">06 - 60</span></li>
                            <li style="text-align: justify;">Nếu hôm trước lô nổ cặp <span style="color: #ff0000;">24 -
                                    42</span> thì hôm sau nuôi cặp <span style="color: #ff0000;">27 - 72</span></li>
                            <li style="text-align: justify;">Hôm trước kết quả trả cặp <span style="color: #ff0000;">78
                                    - 87</span> thì hôm sau để ý con <span style="color: #ff0000;">48 - 84</span></li>
                            <li style="text-align: justify;">Nếu thấy cặp <span style="color: #ff0000;">36 - 63</span>
                                thì hôm sau đánh cặp <span style="color: #ff0000;">38 - 83</span></li>
                            <li style="text-align: justify;">Nếu cặp <span style="color: #ff0000;">47 - 74</span> xuất
                                hiện thì hôm sau đánh cặp <span style="color: #ff0000;">79 - 97</span></li>
                            <li style="text-align: justify;">Nếu thấy số <span style="color: #ff0000;">45 - 54</span>
                                thì hôm sau thử cặp <span style="color: #ff0000;">56 - 95</span></li>
                            <li style="text-align: justify;">Nếu hôm trước về cặp <span style="color: #ff0000;">79 -
                                    97</span> thì hôm sau đánh cặp <span style="color: #ff0000;">37 - 73</span></li>
                            <li style="text-align: justify;">Hôm trước nổ cặp <span style="color: #ff0000;">23 -
                                    32</span> thì hôm sau cặp <span style="color: #ff0000;">54 - 45</span> sẽ về</li>
                            <li style="text-align: justify;">Hôm trước về cặp <span style="color: #ff0000;">14 -
                                    41</span> thì hôm sau về cặp <span style="color: #ff0000;">17 - 71</span></li>
                            <li style="text-align: justify;">Kết quả trả về cặp<span style="color: #ff0000;"> 05 -
                                    50</span> thì hôm sau về cặp <span style="color: #ff0000;">36 - 63</span></li>
                            <li style="text-align: justify;">Hôm trước ra cặp <span style="color: #ff0000;">06 -
                                    60</span> thì hôm sau đừng bỏ qua cặp <span style="color: #ff0000;">06 - 60</span>
                            </li>
                            <li style="text-align: justify;">Hôm trước về cặp <span style="color: #ff0000;">69 -
                                    96</span> thì hôm sau con <span style="color: #ff0000;">71</span> chắc về</li>
                        </ul>
                        <p style="text-align: center;"><span style="color: #ff0000;"><strong></strong></span></p>
                        <p style="text-align: center;"><span style="color: #ff0000;"><strong>» <a
                                        href="/ket-qua-xsmn-xo-so-kien-thiet-mien-nam-sxmn-kqxsmn.html">KQXSMN</a> «</strong></span>
                        </p>
                        <h3 id="trick2" style="text-align: justify;">Những cặp lô hay về theo các thứ trong tuần</h3>
                        <ul>
                            <li style="text-align: justify;">Con số <span style="color: #ff0000;">33</span> hay về vào
                                các ngày Thứ 2, Thứ 3, Thứ 7 và Chủ nhật</li>
                            <li style="text-align: justify;">Thứ 3 hay trả về con số <span
                                    style="color: #ff0000;">46</span></li>
                            <li style="text-align: justify;">Con <span style="color: #ff0000;">66</span> hay nổ vào Thứ
                                4, Thứ 5, Thứ 6</li>
                            <li style="text-align: justify;">Số <span style="color: #ff0000;">56</span> hay về vào Thứ 5
                                và Chủ nhật</li>
                            <li style="text-align: justify;">Thứ 6 thì con<span style="color: #ff0000;"> 81</span> hay
                                nổ nhiều</li>
                            <li style="text-align: justify;">Ngày thứ 7 thì hay về con <span
                                    style="color: #ff0000;">97</span></li>
                            <li style="text-align: justify;">Chủ nhật thì con <span style="color: #ff0000;">58</span>
                                hay về</li>
                        </ul>
                        <p><img src="/media/kinh-nghiem-lo-de/cac-cap-lo-hay-di-ve-cung-nhau.png"
                                alt="cac cap lo hay di cung nhau" width="555" height="258"
                                style="display: block; margin-left: auto; margin-right: auto;"></p>
                        <p style="text-align: center;"><span style="color: #ff0000;"><strong></strong></span></p>
                        <p style="text-align: center;"><span style="color: #ff0000;"><strong>» <a
                                        href="/ket-qua-xsmt-xo-so-kien-thiet-mien-trung-sxmt-kqxsmt.html">KQXSMT</a> «</strong></span></p>
                        <h3 id="trick3" style="text-align: justify;">Những con lô hay đi cùng với giải đặc biệt</h3>
                        <ul>
                            <li style="text-align: justify;">Giải đặc biệt về <span style="color: #ff0000;">05</span>
                                thì hôm sau anh em nên đánh con <span style="color: #ff0000;">95</span></li>
                            <li style="text-align: justify;">Giải ĐB là con <span style="color: #ff0000;">29</span> thì
                                hôm sau sẽ có con lô <span style="color: #ff0000;">22</span> và ngược lại</li>
                            <li style="text-align: justify;">Đặc biệt về con <span style="color: #ff0000;">09</span> thì
                                hôm sau về con <span style="color: #ff0000;">05</span></li>
                            <li style="text-align: justify;">Đề về tổng <span style="color: #ff0000;">10</span> thì hôm
                                sau rơi lại tổng <span style="color: #ff0000;">1</span></li>
                            <li style="text-align: justify;">Giải đặc biệt về <span style="color: #ff0000;">23</span>
                                thì hôm sau nuôi con <span style="color: #ff0000;">48</span></li>
                            <li style="text-align: justify;">Đặc biệt về con <span style="color: #ff0000;">43</span> thì
                                hôm sau lô nổ con số <span style="color: #ff0000;">12</span></li>
                            <li style="text-align: justify;">Nếu giải đặc biệt là đuôi <span
                                    style="color: #ff0000;">92</span> thì hôm sau nên đánh con <span
                                    style="color: #ff0000;">21</span></li>
                            <li style="text-align: justify;">Giải đặc biệt có đuôi<span style="color: #ff0000;">
                                    19</span> thì hôm sau nên chú ý con <span style="color: #ff0000;">36</span></li>
                            <li style="text-align: justify;">Giải ĐB có đuôi <span style="color: #ff0000;">18</span> thì
                                hôm sau anh em đánh con<span style="color: #ff0000;"> 67</span></li>
                        </ul>
                        <h3 id="trick4">3 cặp số hay đi kèm nhau về nhiều nhất</h3>
                        <ul>
                            <li>Con <span style="color: #ff0000;">25</span> và <span style="color: #ff0000;">52</span>
                                hay về cùng con số <span style="color: #ff0000;">22</span></li>
                            <li>Cặp số <span style="color: #ff0000;">36</span> và <span
                                    style="color: #ff0000;">49</span> sẽ nổ cùng với con <span
                                    style="color: #ff0000;">81</span></li>
                            <li>2 con số <span style="color: #ff0000;">64</span> và <span
                                    style="color: #ff0000;">63</span> thường nổ cùng với con số <span
                                    style="color: #ff0000;">85</span></li>
                            <li>Số <span style="color: #ff0000;">32</span> và <span style="color: #ff0000;">43</span>
                                thường về cùng con <span style="color: #ff0000;">91</span></li>
                            <li>Số <span style="color: #ff0000;">99</span> và <span style="color: #ff0000;">00</span>
                                thì về cùng con <span style="color: #ff0000;">50</span></li>
                        </ul>
                        <p style="text-align: justify;">Nếu anh em thích chơi 3 cặp số hoặc đánh lô xiên 3 thì anh em
                            nên tham khảo các cặp số trên để đem lại may mắn cho mình.</p>
                        <p style="text-align: justify;">Lựa chọn các cặp số hay đi cùng nhau là phương án khá hiệu quả
                            để anh em có thể thử vận may. Anh em nên lưu lại các con số này để đem lại may mắn cho mình.
                            Tuy nhiên anh em chỉ nên chơi một cách vui vẻ để giải trí, không nên bỏ quá nhiều tiền vào
                            trò chơi này. Anh em có thể tham khảo thêm các con số may mắn khác tại <a
                                href="/soi-cau-3-mien-du-doan-xo-so-3-mien.html">Soi cầu 3 miền</a>, <a
                                href="/soi-cau-wap-du-doan-xsmb-wap-hom-nay-chinh-xac-nhat.html">Dự đoán XSMB
                                WAP</a>,...</p>
                    </div>
                </div>
                <h3 class="title-bg-blue border-radius-top mb-0"> Bi kíp chơi lô đề</h3>
                <div class="border border-radius-bottom px-3 pb-3">
                    <div class="row">
                        <div class="col-12 mt-3 mb-2"> <a class="text-blue1 font-16 font-weight-bold"
                                href="/nen-danh-de-1-con-hay-nhieu-con-d364.html"
                                title="Nên đánh đề 1 con hay nhiều con để về bờ nhanh chóng?">Nên đánh đề 1 con hay
                                nhiều con để về bờ nhanh chóng?</a> </div>
                        <div class="col-4 pr-2"> <a href="/nen-danh-de-1-con-hay-nhieu-con-d364.html"
                                title="Nên đánh đề 1 con hay nhiều con để về bờ nhanh chóng?"> <img loading="lazy"
                                    width="410" height="215"
                                    src="/media/thumb/kinh-nghiem-lo-de/Lo-khung-3-ngay-4-410x215.jpg"
                                    alt="Nên đánh đề 1 con hay nhiều con để về bờ nhanh chóng?"> </a> </div>
                        <div class="col-8 pl-2">
                            <p class="text-black1 font-14 lh-18px line-3 text-justify"></p>
                            <p>Xổ số do nhà nước tổ chức có 27 lần quay, mỗi lần mở thưởng chỉ có một con số may mắn sẽ
                                về. Vì vậy cách đánh nào sẽ có xác suất trúng cao? Đánh 1 con hay nhiều con?</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-3 mb-2"> <a class="text-blue1 font-16 font-weight-bold"
                                href="/tong-hop-meo-choi-lo-de-it-thua-lo-d351.html"
                                title="Tổng hợp mẹo chơi lô đề ít thua lỗ nhất từ chuyên gia lô đề">Tổng hợp mẹo chơi lô
                                đề ít thua lỗ nhất từ chuyên gia lô đề</a> </div>
                        <div class="col-4 pr-2"> <a href="/tong-hop-meo-choi-lo-de-it-thua-lo-d351.html"
                                title="Tổng hợp mẹo chơi lô đề ít thua lỗ nhất từ chuyên gia lô đề"> <img loading="lazy"
                                    width="410" height="215"
                                    src="/media/thumb/kinh-nghiem-lo-de/cach-choi-lo-de-it-thua-lo-410x215.jpg"
                                    alt="Tổng hợp mẹo chơi lô đề ít thua lỗ nhất từ chuyên gia lô đề"> </a> </div>
                        <div class="col-8 pl-2">
                            <p class="text-black1 font-14 lh-18px line-3 text-justify">Anh em lô thủ nào khi chơi lô đề
                                cũng đều mong muốn có lãi. Nhưng trò giải trí này có độ may rủi cao nên cần suy nghĩ kỹ
                                càng trước khi đầu tư. Việc chơi sao không lỗ vốn là vô cùng quan trọng.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-3 mb-2"> <a class="text-blue1 font-16 font-weight-bold"
                                href="/5-kinh-nghiem-khi-choi-lo-de-online-hieu-qua-d338.html"
                                title="5 kinh nghiệm khi chơi lô đề online hiệu quả từ chuyên gia">5 kinh nghiệm khi
                                chơi lô đề online hiệu quả từ chuyên gia</a> </div>
                        <div class="col-4 pr-2"> <a href="/5-kinh-nghiem-khi-choi-lo-de-online-hieu-qua-d338.html"
                                title="5 kinh nghiệm khi chơi lô đề online hiệu quả từ chuyên gia"> <img loading="lazy"
                                    width="410" height="215"
                                    src="/media/thumb/kinh-nghiem-lo-de/kinh-nghiem-danh-lo-de-online-1-410x215.jpg"
                                    alt="5 kinh nghiệm khi chơi lô đề online hiệu quả từ chuyên gia"> </a> </div>
                        <div class="col-8 pl-2">
                            <p class="text-black1 font-14 lh-18px line-3 text-justify"></p>
                            <p>Chơi lô đề online được nhiều anh em tham gia vì sự tiện lợi của nó. Nhưng có những điều
                                cần lưu ý khi chơi mà không phải ai cũng biết.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-3 mb-2"> <a class="text-blue1 font-16 font-weight-bold"
                                href="/cach-tinh-bong-so-de-cuc-hay-d331.html"
                                title="Bóng số đề là gì? Cách tính bóng số đề cực hay">Bóng số đề là gì? Cách tính bóng
                                số đề cực hay</a> </div>
                        <div class="col-4 pr-2"> <a href="/cach-tinh-bong-so-de-cuc-hay-d331.html"
                                title="Bóng số đề là gì? Cách tính bóng số đề cực hay"> <img loading="lazy" width="410"
                                    height="215" src="/media/thumb/kinh-nghiem-lo-de/bong-so-de-410x215.jpg"
                                    alt="Bóng số đề là gì? Cách tính bóng số đề cực hay"> </a> </div>
                        <div class="col-8 pl-2">
                            <p class="text-black1 font-14 lh-18px line-3 text-justify">Xác định con lô đẹp theo bóng số
                                đề là cách soi lô vô cùng hiệu quả. Rất nhiều anh em giành giải thưởng lớn khi dùng
                                phương pháp này. Kinh nghiệm tính bóng lô đề hay nhất được truyền lại từ các cao thủ sẽ
                                nằm trong bài viết dưới đây.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mt-3 mb-2"> <a class="text-blue1 font-16 font-weight-bold"
                                href="/bi-kip-danh-so-de-12-con-giap-chinh-xac-tuyet-dinh-d323.html"
                                title="Bí kíp đánh số đề 12 con giáp chính xác tuyệt đỉnh">Bí kíp đánh số đề 12 con giáp
                                chính xác tuyệt đỉnh</a> </div>
                        <div class="col-4 pr-2"> <a href="/bi-kip-danh-so-de-12-con-giap-chinh-xac-tuyet-dinh-d323.html"
                                title="Bí kíp đánh số đề 12 con giáp chính xác tuyệt đỉnh"> <img loading="lazy"
                                    width="410" height="215"
                                    src="/media/thumb/kinh-nghiem-lo-de/danh-so-de-12-con-giap-410x215.jpg"
                                    alt="Bí kíp đánh số đề 12 con giáp chính xác tuyệt đỉnh"> </a> </div>
                        <div class="col-8 pl-2">
                            <p class="text-black1 font-14 lh-18px line-3 text-justify">Bộ số đề 12 con giáp giúp anh em
                                lô thủ tìm được dàn đề nhanh chóng và chính xác nhất. Cách đánh này không quá xa lạ với
                                anh em lô thủ, đây là một trong những phương pháp chốt cầu lô đẹp anh em nên sử dụng.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- SIDEBAR LEFT (col-xl-200) -->
            <div class="col-xl-200 mx-lg-3 mx-lg-0 pr-md-3 pr-lg-0 order-2 order-lg-1 font-14">
                <?php $this->partial('partials/sidebar_left'); ?>
            </div>

            <!-- SIDEBAR RIGHT (col-xl-300) -->
            <div class="col-xl-300 mt-3 mt-md-0 order-1 order-lg-2">
                <?php $this->partial('partials/sidebar_right'); ?>
            </div>

        </div>
</main>