<?php date_default_timezone_set('Asia/Ho_Chi_Minh'); ?>
<div class="util-bg-white util-shadow-sm util-mb-3">
    <div class="layout-wrapper">
        <div class="layout-row">
            <div class="layout-col-12">
                <ul class="nav-sub">
                    <li><a title="Trực tiếp kết quả xổ số Miền Bắc" href="/truc-tiep-ket-qua-xo-so-mien-bac-ttxsmb-xsmb.html">Trực tiếp XSMB</a></li>
                    <li><a title="Trực tiếp kết quả xổ số Miền Nam" href="/truc-tiep-ket-qua-xo-so-mien-nam-ttxsmn-xsmn.html">Trực tiếp XSMN</a></li>
                    <li><a class="util-text-red" title="Trực tiếp kết quả xổ số Miền Trung" href="/truc-tiep-ket-qua-xo-so-mien-trung-ttxsmt-xsmt.html">Trực tiếp XSMT</a></li>
                    <li><a title="Trực tiếp kết quả xổ số Mega 6/45 Vietlott" href="/truc-tiep-ket-qua-xo-so-mega-6-45-vietlott.html">Live Mega 6/45</a></li>
                    <li><a title="Trực tiếp kết quả xổ số Power 6/55 Vietlott" href="/truc-tiep-ket-qua-xo-so-power-6-55-vietlott.html">Live Power 6/55</a></li>
                    <li><a title="Trực tiếp kết quả xổ số Max 3D Vietlott" href="/truc-tiep-ket-qua-xo-so-max-3d-vietlott.html">Live Max 3D</a></li>
                    <li><a title="Trực tiếp kết quả xổ số Max 3D Pro Vietlott" href="/truc-tiep-ket-qua-xo-so-max-3d-pro-vietlott.html">Live Max 3D Pro</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<main class="layout-wrapper-fluid util-mt-3 util-px-0 util-px-md-3 layout-clearfix">
    <div class="layout-row util-g-0 util-g-md-3">
        <div class="layout-col-12 layout-col-lg-8">
            <div class="util-mx-1">
                <nav aria-label="breadcrumb">
                    <ol class="nav-breadcrumb layout-clearfix util-mb-3">
                        <li class="nav-breadcrumb-item"><a title="Trang chủ" href="/"><span>Trang chủ</span></a></li>
                        <li class="nav-breadcrumb-item"><a title="Xổ số Miền Trung" href="/ket-qua-xsmt-xo-so-kien-thiet-mien-trung-sxmt-kqxsmt.html"><span>Xổ số Miền Trung</span></a></li>
                        <li class="nav-breadcrumb-item"><span>XSMT <?php echo date('d/m/Y'); ?></span></li>
                    </ol>
                </nav>

                <div class="page-header">
                    <h1 class="page-title-h1 util-mb-3 util-p-2 util-px-3 util-border util-border-danger util-rounded util-shadow-sm">XSMT <?php echo date('d/m/Y'); ?> – Kết Quả Xổ Số Miền Trung Ngày <?php echo date('d/m/Y'); ?></h1>
                </div>
            </div>
            <div class="comp-article-content util-bg-white util-shadow-sm util-mb-3">
                <h2 class="util-fs-6 util-font-medium util-lh-base util-p-3">XSMT <?php echo date('d/m/Y'); ?>, Cập nhật kết quả xổ số Miền Trung ngày <?php echo date('d/m/Y'); ?> đầy đủ và chính xác nhất được công bố từ hội đồng xổ số kiến thiết Miền Trung.</h2>
            </div>
            <div class="comp-article-content util-bg-white util-shadow-sm util-mb-3" style="border-left: none;">
                <div class="live-banner">
                    <span class="live-dot">🔴 LIVE</span>
                    <span class="text-live">
                        Cập nhật kết quả xổ số Miền Trung (XSMT) trực tiếp vào lúc <strong>17h15</strong> hôm nay <?php echo date('d/m/Y'); ?>,
                        nhanh chóng – chính xác – uy tín, được công bố từ hội đồng xổ số kiến thiết Miền Trung.
                    </span>
                    <div class="continuous-4">
                    </div>

                </div>
            </div>



            <div id="position-<?php echo date('Ymd'); ?>" class="lottery-result js-table-result js-table-xsmt" data-ketqua="22593,22596,22597,22598" data-mien="Xổ Số Miền Trung">
                <header class="lottery-result-header util-sticky-top">
                    <div class="breadcrumb-nav">
                        <h2 class="lottery-result-title">
                            <a href="/ket-qua-xsmt-xo-so-kien-thiet-mien-trung-sxmt-kqxsmt.html" title="Kết quả xổ số Miền Trung">XSMT</a>
                            <span class="sep">»</span>
                            <span class="breadcrumb-current">XSMT <?php echo $this->view->currentDayName; ?></span>
                            <span class="sep">»</span>
                            <span class="breadcrumb-current">XSMT <?php echo date('d/m/Y'); ?></span>
                        </h2>
                    </div>
                </header>
                <table class="comp-table util-align-items-center lottery-table xsmt js-lottery-kq-table">
                    <thead class="table-header util-sticky-top util-align-items-center">
                        <tr>
                            <th class="util-small util-text-start util-bg-primary-subtle" style="--i:0">Giải</th>
                            <?php $i = 1;
                            foreach ($this->view->provincesForView as $province): ?>
                                <th class="util-bg-primary-subtle" style="--i:<?php echo $i; ?>">
                                    <a href="/ket-qua-xo-so-<?= strtolower(str_replace(' ', '-', $province['name'])) ?>-<?= strtolower($province['code']) ?>.html"
                                        title="Kết quả xổ số <?php echo $province['name']; ?>"
                                        aria-label="Xem kết quả xổ số <?php echo $province['name']; ?>">
                                        <?php echo $province['name']; ?>
                                    </a>
                                </th>
                            <?php $i++;
                            endforeach; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="util-small util-text-start">Giải 8</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number big" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="9" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 7</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="8" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 6</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="7" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 5</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="6" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 4</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="5" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 3</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="4" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 2</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="3" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-start">Giải 1</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="2" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td class="util-small util-text-nowrap util-text-start">Giải ĐB</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td><span class="lottery-number medium" data-page-id="<?php echo $province['keyid']; ?>" data-id-giai="1" data-num=""><span class="spinner-border spinner-border-sm util-text-warning util-fs-6" role="status"></span></span></td>
                            <?php endforeach; ?>
                        </tr>
                        <tr>
                            <td colspan="<?php echo count($this->view->provincesForView) + 1; ?>" class="util-bg-primary-subtle util-p-2 util-text-start">
                                Lô tô Miền Trung - <?php echo $this->view->currentDayName; ?> Ngày <?php echo date('d/m/Y'); ?>
                            </td>
                        </tr>
                        <tr class="util-align-items-center">
                            <td>Đầu</td>
                            <?php foreach ($this->view->provincesForView as $province): ?>
                                <td class="lotto-number-cell">
                                    <?php echo $province['code']; ?>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                        <?php for ($i = 0; $i <= 9; $i++): ?>
                            <tr style="--lotto-delay:<?php echo $i + 1; ?>">
                                <td class="util-text-red util-font-bold"><?php echo $i; ?></td>
                                <?php foreach ($this->view->provincesForView as $province): ?>
                                    <td class="lotto-number-cell js-number-dau-duoi" data-find="dau" data-page-id="<?php echo $province['keyid']; ?>" data-num="<?php echo $i; ?>">
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endfor; ?>
                    </tbody>
                </table>
                <div class="comp-article-content util-p-3 util-bg-white util-shadow-sm -mt-5 util-rounded js-bottom-content">
                    <p>Để thuận tiện tham gia dự thưởng Miền Trung, mời các bạn tham khảo lịch quay sau đây:</p>
                    <h3><strong>Lịch mở thưởng <a title="xổ số Miền Trung" href="/ket-qua-xsmt-xo-so-kien-thiet-mien-trung-sxmt-kqxsmt.html">xổ số Miền Trung</a></strong></h3>

                    <p>Thứ 2: <a title="Thừa Thiên Huế" href="/ket-qua-xo-so-thua-thien-hue-xstth.html">Huế</a>, <a title="Phú Yên" href="/ket-qua-xo-so-phu-yen-xspy.html">Phú Yên</a></p>
                    <p>Thứ 3: <a title="Đắk Lắk" href="/ket-qua-xo-so-dak-lak-xsdaklak.html">Đắk Lắk</a>, <a title="Quảng Nam" href="/ket-qua-xo-so-quang-nam-xsqn.html">Quảng Nam</a></p>
                    <p>Thứ 4: <a title="Đà Nẵng" href="/ket-qua-xo-so-da-nang-xsdanang.html">Đà Nẵng</a>, <a title="Khánh Hòa" href="/ket-qua-xo-so-khanh-hoa-xskh.html">Khánh Hòa</a></p>
                    <p>Thứ 5: <a title="Bình Định" href="/ket-qua-xo-so-binh-dinh-xsbd.html">Bình Định</a>, <a title="Quảng Trị" href="/ket-qua-xo-so-quang-tri-xsqt.html">Quảng Trị</a>, <a title="Quảng Bình" href="/ket-qua-xo-so-quang-binh-xsqb.html">Quảng Bình</a></p>
                    <p>Thứ 6: <a title="Gia Lai" href="/ket-qua-xo-so-gia-lai-xsgl.html">Gia Lai</a>, <a title="Ninh Thuận" href="/ket-qua-xo-so-ninh-thuan-xsnth.html">Ninh Thuận</a></p>
                    <p>Thứ 7: <a title="Đà Nẵng" href="/ket-qua-xo-so-da-nang-xsdanang.html">Đà Nẵng</a>, <a title="Quảng Ngãi" href="/ket-qua-xo-so-quang-ngai-xsqng.html">Quảng Ngãi</a>, <a title="Đắk Nông" href="/ket-qua-xo-so-dak-nong-xsdn.html">Đắk Nông</a></p>
                    <p>Chủ Nhật: <a title="Khánh Hòa" href="/ket-qua-xo-so-khanh-hoa-xskh.html">Khánh Hòa</a>, <a title="Kon Tum" href="/ket-qua-xo-so-kon-tum-xskontum.html">Kon Tum</a>, <a title="Thừa Thiên Huế" href="/ket-qua-xo-so-thua-thien-hue-xstth.html">Huế</a></p>

                    <p><strong>Chúc bạn may mắn trúng thưởng!</strong></p>
                </div>
            </div>
        </div>
        <?php $this->partial('layouts/rightbar'); ?>
    </div>
</main>
<link rel="stylesheet" href="/css/live-animations.css">
<link rel="preload" href="/js/live/limt.js" as="script">
<script>
    window.appProvinces = <?php echo json_encode($this->view->provinces); ?>;
    window.baseUrl = '<?php echo $this->view->baseUrl; ?>';
</script>
<script src="/js/live/limt.js" async></script>