<footer class="bg-blue1 font-13">
    <div class="container">
        <div class="text-center footer-top">
            <div class="box-logo"> <img loading="lazy" width="156" height="39" class="logo"
                    src="/media/website/logo-footer.svg" alt="Soi Cầu 247"> </div>
            <div>
                <p class="mb-0">Chuyên trang Phân tích, soi cầu, thống kê và Tường thuật trực tiếp kết quả xổ số Ba
                    Miền nhanh nhất, chính xác nhất.</p>
                <p class="mb-0">Liên hệ: <a rel="nofollow" style="color: #81A7B8"
                        href="cdn-cgi/l/email-protection.html#ceb8a0afaabdfcfaf98ea9a3afa7a2e0ada1a3"><span
                            class="__cf_email__"
                            data-cfemail="a3d5cdc2c7d0919794e3c4cec2cacf8dc0ccce">[email&#160;protected]</span></a>
                </p>
                <p class="mb-0">Liên hệ Telegram: <a rel="nofollow" style="color: #81A7B8"
                        href="https://t.me/npadsvn">https://t.me/npadsvn</a></p>
                <p class="mb-0">247 Trần Duy Hưng, Trung Hoà, Cầu Giấy, Hà Nội, Việt Nam</p>
                <p class="mb-0">Hotline: 0946025318</p>
                <ul class="mt-3">
                    <li> <a href="https://www.facebook.com/soicau247.ads/" rel="nofollow" target="_blank"
                            title="facebook"> <i class="icon-facebook2 text-white"></i> </a> </li>
                    <li> <a href="https://twitter.com/SoiCau2472" rel="nofollow" target="_blank" title="facebook">
                            <i class="icon-twitter text-white"></i> </a> </li>
                    <li> <a href="https://www.instagram.com/soicau247blog/" rel="nofollow" target="_blank"
                            title="facebook"> <i class="icon-instagram text-white"></i> </a> </li>
                    <li> <a href="https://www.youtube.com/channel/UCSr1w1o5IZXdw4P7BXsA7hg" rel="nofollow"
                            target="_blank" title="facebook"> <i class="icon-youtube text-white"></i> </a> </li>
                    <li> <a href="https://www.pinterest.com/soicau247ads/" rel="nofollow" target="_blank"
                            title="facebook"> <i class="icon-pinterest text-white"></i> </a> </li>
                </ul> <a href="http://www.dmca.com/Protection/Status.aspx?ID=43d5ecca-f882-4574-93da-97a53ad681a1"
                    title="DMCA.com Protection Status" class="dmca-badge"> <img width="135" height="28" loading="lazy"
                        src="https://images.dmca.com/Badges/_dmca_premi_badge_4.png?ID=43d5ecca-f882-4574-93da-97a53ad681a1"
                        alt="DMCA.com Protection Status" /> </a>
            </div>
        </div>
        <div class="row footer-bottom">
            <ul class="nav ">
                <li class="nav-item"><a class='nav-link' href='gioi-thieu.html' title='Giới thiệu'>Giới thiệu</a>
                </li>
                <li class="nav-item"><a class='nav-link' href='dieu-khoan-su-dung.html' title='Điều khoản sử dụng'>Điều
                        khoản sử dụng</a></li>
                <li class="nav-item"><a class='nav-link' href='chinh-sach-bao-mat.html' title='Chính sách bảo mật'>Chính
                        sách bảo mật</a></li>
                <li class="nav-item"><a class='nav-link' href='lien-he.html' title='Liên hệ'>Liên hệ</a></li>
            </ul>
        </div>
    </div>
    <div class="border-bottom"></div>
    <div class="container">
        <div class="row footer-bottom">

            <div class="d-lg-flex justify-content-between p-2 order-lg-1 flex-grow-1">
                <p class="mb-0">Copyright © 2020 by soicau247.com</p>
                <p class="mb-0">All rights reserved hts reserved</p>
            </div>
        </div>
    </div>
</footer>